Source/KGERP/Controllers/CompanySubMenusController.cs
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using KGERP.ViewModel;
using PagedList;
using System.Collections.Generic;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [CheckSession]
    public class CompanySubMenusController : Controller
    {
        private readonly ICompanyMenuService companyMenuService;
        private readonly ICompanyService companyService;
        private readonly ICompanySubMenuService companySubMenuService;

        public CompanySubMenusController(ICompanyMenuService companyMenuService, ICompanyService companyService,
            ICompanySubMenuService companySubMenuService)
        {
            this.companyMenuService = companyMenuService;
            this.companyService = companyService;
            this.companySubMenuService = companySubMenuService;
        }

        
        [HttpGet]
        public ActionResult Index(int? Page_No, string searchText)
        {
            searchText = searchText ?? "";
            List<CompanySubMenuModel> companySubMenus = companySubMenuService.GetCompanySubMenus(searchText);
            int Size_Of_Page = 10;
            int No_Of_Page = (Page_No ?? 1);
            return View(companySubMenus.ToPagedList(No_Of_Page, Size_Of_Page));
        }


        [HttpGet]
        
        public ActionResult CreateOrEdit(int id)
        {
            CompanySubMenuViewModel vm = new CompanySubMenuViewModel();
            vm.CompanySubMenu = companySubMenuService.GetCompanySubMenu(id);
            vm.Companies = companyService.GetAllCompanySelectModels();

            if (vm.CompanySubMenu.CompanySubMenuId > 0)
            {
                vm.CompanyMenus = companyMenuService.GetCompanyMenuSelectModelsByCompanyId(vm.CompanySubMenu.CompanyId);
            }
            else
            {
                vm.CompanyMenus = new List<SelectModel>();
            }
            return View(vm);

        }



        [HttpPost]
        
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(CompanySubMenuViewModel vm)
        {
            bool result = false;
            if (vm.CompanySubMenu.CompanySubMenuId <= 0)
            {
                result = companySubMenuService.SaveCompanySubMenu(0, vm.CompanySubMenu);
            }
            else
            {
                result = companySubMenuService.SaveCompanySubMenu(vm.CompanySubMenu.CompanySubMenuId, vm.CompanySubMenu);
            }
            return RedirectToAction("Index");
        }



        [HttpPost]
        
        public JsonResult GetCompanySubMenuSelectModelsByCompanyMenu(int menuId)
        {
            List<SelectModel> companySubMenus = companySubMenuService.GetCompanySubMenuSelectModelsByCompanyMenu(menuId);
            return Json(companySubMenus, JsonRequestBehavior.AllowGet);
        }



        // GET: SubMenus/Delete/5
        public ActionResult Delete(int? id)
        {
            bool result = companySubMenuService.DeleteCompanySubMenu(id);
            if (result)
            {
                TempData["message"] = "Deleted Successfully";
            }
            else
            {
                TempData["message"] = "Sorry! Data Not Deleted";
            }
            return RedirectToAction("Index");
        }



        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Source/KGERP/Views/CompanySubMenus/Create.cshtml
@model KGERP.ViewModel.CompanyMenuViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CompanyMenu.CompanyMenuId)

    <div class="form-horizontal">
        <h4>Comapny Menu @Model.CompanyMenu.ButtonName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyMenu.CompanyId, new SelectList(Model.Companies, "Value", "Text"), "--Select--", htmlAttributes: new { @class = "dropdownsize form-control" })
                @Html.ValidationMessageFor(model => model.CompanyMenu.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyMenu.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyMenu.Name, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
                @Html.LabelFor(model => model.CompanyMenu.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyMenu.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
  


        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CompanyMenu.IsActive)
                    @Html.ValidationMessageFor(model => model.CompanyMenu.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Model.CompanyMenu.ButtonName" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { companyId = Request.QueryString["companyId"] })
</div>

Source/KGERP/Views/CompanySubMenus/CreateOrEdit.cshtml
@model KGERP.ViewModel.CompanySubMenuViewModel
@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("CreateOrEdit", "CompanySubMenus", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <span style="font-size:25px">Sub Menu</span>
        <hr style="border-color:#32527B; padding:0px;margin-top: 10px;margin-bottom: 10px; border-width: 2px;" />
    </div>

    <div class="form-horizontal">
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CompanySubMenu.CompanySubMenuId)
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanySubMenu.CompanyId, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.CompanySubMenu.CompanyId, new SelectList(Model.Companies, "Value", "Text"), "---Select---", new { @class = "dropdownsize form-control", @id = "ddlCompany" })
                        @Html.ValidationMessageFor(model => model.CompanySubMenu.CompanyId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanySubMenu.CompanyMenuId, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.CompanySubMenu.CompanyMenuId, new SelectList(Model.CompanyMenus, "Value", "Text"), "--Select--", new { @class = "dropdownsize form-control", @id = "ddlCompanyMenu" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanySubMenu.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CompanySubMenu.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanySubMenu.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanySubMenu.OrderNo, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CompanySubMenu.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanySubMenu.OrderNo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanySubMenu.Controller, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CompanySubMenu.Controller, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanySubMenu.Controller, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanySubMenu.Action, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CompanySubMenu.Action, new { htmlAttributes = new { @class = "form-control"} })
                        @Html.ValidationMessageFor(model => model.CompanySubMenu.Action, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>



            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanySubMenu.Param, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CompanySubMenu.Param, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompanySubMenu.Param, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CompanySubMenu.IsActive, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CompanySubMenu.IsActive)
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <input type="submit" value="@Model.CompanySubMenu.ButtonName" id="apply" class="btn btn-primary pull-right" />
                    <a href="@Url.Action("Index",new {parentId=Request.QueryString["parentId"]})" class="btn btn-danger pull-right" style="margin-right:8px">
                        Close <i class="fa fa-close" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

        $('#ddlCompany').change(function () {
            $.ajax({
                type: "post",
                url: "/CompanyMenus/GetCompanyMenuSelectModelsByCompany",
                data: { companyId: $('#ddlCompany').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    var companyMenu = "<select>";
                    companyMenu = companyMenu + '<option value="">--Select--</option>';
                    for (var i = 0; i < data.length; i++) {
                        companyMenu = companyMenu + '<option value=' + data[i].Value + '>' + data[i].Text + '</option>';
                    }
                    companyMenu = companyMenu + '</select>';
                    $('#ddlCompanyMenu').html(companyMenu);
                }
            });
        });

        
    </script>

}

Source/KGERP/Views/CompanySubMenus/Delete.cshtml
@model KGERP.ViewModel.CompanyMenuViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CompanyMenu.CompanyMenuId)

    <div class="form-horizontal">
        <h4>Comapny Menu @Model.CompanyMenu.ButtonName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyMenu.CompanyId, new SelectList(Model.Companies, "Value", "Text"), "--Select--", htmlAttributes: new { @class = "dropdownsize form-control" })
                @Html.ValidationMessageFor(model => model.CompanyMenu.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyMenu.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyMenu.Name, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
                @Html.LabelFor(model => model.CompanyMenu.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyMenu.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
  


        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CompanyMenu.IsActive)
                    @Html.ValidationMessageFor(model => model.CompanyMenu.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Model.CompanyMenu.ButtonName" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { companyId = Request.QueryString["companyId"] })
</div>

Source/KGERP/Views/CompanySubMenus/Details.cshtml
@model KGERP.ViewModel.CompanyMenuViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CompanyMenu.CompanyMenuId)

    <div class="form-horizontal">
        <h4>Comapny Menu @Model.CompanyMenu.ButtonName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyMenu.CompanyId, new SelectList(Model.Companies, "Value", "Text"), "--Select--", htmlAttributes: new { @class = "dropdownsize form-control" })
                @Html.ValidationMessageFor(model => model.CompanyMenu.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyMenu.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyMenu.Name, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
                @Html.LabelFor(model => model.CompanyMenu.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyMenu.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
  


        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CompanyMenu.IsActive)
                    @Html.ValidationMessageFor(model => model.CompanyMenu.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Model.CompanyMenu.ButtonName" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { companyId = Request.QueryString["companyId"] })
</div>

Source/KGERP/Views/CompanySubMenus/Edit.cshtml
@model KGERP.ViewModel.CompanyMenuViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CompanyMenu.CompanyMenuId)

    <div class="form-horizontal">
        <h4>Comapny Menu @Model.CompanyMenu.ButtonName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyMenu.CompanyId, new SelectList(Model.Companies, "Value", "Text"), "--Select--", htmlAttributes: new { @class = "dropdownsize form-control" })
                @Html.ValidationMessageFor(model => model.CompanyMenu.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyMenu.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyMenu.Name, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
                @Html.LabelFor(model => model.CompanyMenu.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyMenu.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
  


        <div class="form-group">
            @Html.LabelFor(model => model.CompanyMenu.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CompanyMenu.IsActive)
                    @Html.ValidationMessageFor(model => model.CompanyMenu.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Model.CompanyMenu.ButtonName" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { companyId = Request.QueryString["companyId"] })
</div>

Source/KGERP/Views/CompanySubMenus/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<KGERP.Service.ServiceModel.CompanySubMenuModel>
@using PagedList;
@{
    ViewBag.Title = "Index";
    var message = TempData["message"];
}
<link href="~/Content/CustomCss/search-form.css" rel="stylesheet" />

@using (Html.BeginForm("Index", "CompanySubMenus", FormMethod.Get, new { @class = "example" }))
{
    <div class="row">
        <div class="col-md-6">
            <span style="font-size:20px;font-weight:bold">
                Company's Sub Menu
            </span>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.Editor("searchText", new { htmlAttributes = new { @autocomplete = "off", value = "", @placeholder = "Search..." } })
                <button type="submit"><i class="fa fa-search "></i></button>
            </div>
        </div>
        <div class="col-md-2 pull-right">
            <div class="form-group">
                <a href="@Url.Action("CreateOrEdit", new { id = 0})" class="btn btn-primary pull-right">
                    <span class="glyphicon glyphicon-plus"></span> Add
                </a>
            </div>
        </div>
    </div>
}

<div class="row">
    <hr style="border-color:#32527B; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
    <table class="table table-striped table-responsive">
        <tr style="background-color:#3c8dbc;color:#ffffff">
            <th>
                SL.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().CompanyMenu.CompanyId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().CompanyMenuId)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.First().Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.First().OrderNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Controller)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Action)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.First().Param)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.First().IsActive)
            </th>

            <th class="text-center">Action</th>
        </tr>

        @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
        {
            <tr>
                <td width="5%">
                    @((item.Index + 1) + (Model.PageNumber - 1) * Model.PageSize)
                </td>
                <td width="10%">
                    @Html.DisplayFor(modelItem => item.Data.CompanyMenu.Company.ShortName)
                </td>
                <td width="15%">
                    @Html.DisplayFor(modelItem => item.Data.CompanyMenu.Name)
                </td>
                <td width="15%">
                    @Html.DisplayFor(modelItem => item.Data.Name)
                </td>
                <td width="5%">
                    @Html.DisplayFor(modelItem => item.Data.OrderNo)
                </td>

                <td width="15%">
                    @Html.DisplayFor(modelItem => item.Data.Controller)
                </td>

                <td width="10%">

                    @Html.DisplayFor(modelItem => item.Data.Action)
                </td>
                <td width="15%">
                    @Html.DisplayFor(modelItem => item.Data.Param)
                </td>
                <td width="5%">
                    @Html.DisplayFor(modelItem => item.Data.IsActive)
                </td>
                <td nowrap>
                    <a href="@Url.Action("CreateOrEdit", new { id = item.Data.CompanySubMenuId })" title="Edit" class="btn btn-info btn-xs">
                        <i class="fa fa-edit" style="font-size:15px;" aria-hidden="true"></i>
                    </a>

                    <a href="@Url.Action("Delete", new { id = item.Data.CompanySubMenuId})" title="Delete" onclick="return confirm('Are you sure to delete this?');" class="btn btn-danger btn-xs">
                        <i class="fa fa-trash" style="font-size:15px;" aria-hidden="true"></i>
                    </a>


                </td>
            </tr>
        }

    </table>
    @if (Model.PageCount > 1)
    {
        <span class="btn btn-success">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        </span>
        <span class="checkbox">
            @Html.PagedListPager(Model, Page_No => Url.Action("Index", "CompanySubMenus",
                                         new { companyId = Request.QueryString["companyId"], Page_No, SearchText = Request.QueryString["searchText"] }))
        </span>
    }

</div>


@section Scripts{
    <script type="text/javascript">
          var message = '@message';
        if(message){
            alert(message);
        }
    </script>
}