Source/KGERP/Controllers/OfficerAssignController.cs
using KGERP.Data.Models;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using KGERP.ViewModel;
using PagedList;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Windows.Forms;

namespace KGERP.Controllers
{
    [CheckSession]
    public class OfficerAssignController : Controller
    {
        private readonly IZoneService zoneService;
        private readonly IOfficerAssignService officerAssignService;
        public OfficerAssignController(IZoneService zoneService, IOfficerAssignService officerAssignService)
        {
            this.zoneService = zoneService;
            this.officerAssignService = officerAssignService;
        }
        [HttpGet]
        
        public ActionResult Index(int companyId, int? Page_No, string searchText)
        {
            searchText = searchText ?? string.Empty;
            if (companyId > 0)
            {
                Session["CompanyId"] = companyId;
            }
            List<OfficerAssignModel> models = officerAssignService.GetOfficerAssigns(companyId, searchText);
            int Size_Of_Page = 15;
            int No_Of_Page = (Page_No ?? 1);
            return View(models.ToPagedList(No_Of_Page, Size_Of_Page));

        }

        [HttpGet]
        
        public ActionResult CreateOrEdit(int id)
        {
            int companyId = Convert.ToInt32(Session["CompanyId"]);
            OfficerAssignViewModel vm = new OfficerAssignViewModel();
            vm.OfficerAssign = officerAssignService.GetOfficerAssign(id);
            vm.OfficerAssign.CompanyId = companyId;
            if (vm.OfficerAssign.OfficerAssignId > 0)
            {
                vm.OfficerAssign.OfficerName = officerAssignService.GetOffierName(vm.OfficerAssign.EmpId);
            }

            vm.Zones = zoneService.GetZoneSelectModels(companyId);
            return View(vm);
        }

        [HttpGet]
        
        public async Task<ActionResult> ZonewiseEmployeeAssign(int companyId)
        {
            var res=await officerAssignService.OfficersAssign(companyId);
            return View(res);
        }
        [HttpGet]

        public async Task<ActionResult> SalesPersonList(int companyId)
        {
            var res = await officerAssignService.OfficersAssignFoeNewsaleeslist(companyId);
            return View(res);
        }
        [HttpGet]
        
        public ActionResult Create(int CompanyId)
        {
            OfficerAssignModel model= new OfficerAssignModel();
            model.ZoneList = officerAssignService.GetZoneList(CompanyId);
            model.CompanyId = CompanyId;
            return View(model);
        }
        [HttpGet]

        public ActionResult CreateSalesPersn(int CompanyId)
        {
            OfficerAssignModel model = new OfficerAssignModel();
            model.CompanyId = CompanyId;
            return View(model);
        }
        [HttpPost]

        public ActionResult CreateSalesPersn(OfficerAssignModel Model)
        {
            OfficerAssignModel officerAssignmodel = new OfficerAssignModel();
            var obj = officerAssignService.AssignpesronSalePersn(Model);
            return RedirectToAction("SalesPersonList", new { companyId = Model.CompanyId });
        }
        [HttpPost]
        
        public ActionResult Create(OfficerAssignModel Model)
        {
            OfficerAssignModel officerAssignmodel = new OfficerAssignModel();
            var obj = officerAssignService.Assignpesron(Model);
            return RedirectToAction("ZonewiseEmployeeAssign",  new { companyId = 21 });
        }

        [HttpGet]
        
        public ActionResult EditMarketingOfficer(int Id,int companyId)
        {

            var obj= officerAssignService.UpdateMarketingOfficer(Id,companyId);
            return View(obj);
        }

        [HttpPost]
        
        public ActionResult EditMarketingOfficer(OfficerAssignModel model)
        {
            var res = officerAssignService.UpdateOfficer(model);

            return RedirectToAction("ZonewiseEmployeeAssign", new { companyId = 21 });
        }




        [HttpGet]
        
        public JsonResult GetSubZone(int Id)
        {
            OfficerAssignModel model = new OfficerAssignModel();
            model.SubZoneList = officerAssignService.GetSubZoneList(Id);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        
        public ActionResult DeleteOfficer(int Id)
        {
            var res = officerAssignService.DeleteOfficerNew(Id);
            return RedirectToAction("ZonewiseEmployeeAssign", new { companyId = 21 });
        }
        [HttpGet]

        public ActionResult DeleteOfficerSalespersn(int Id,int CompanyId)
        {
            var res = officerAssignService.DeleteOfficerNew(Id);
            return RedirectToAction("SalesPersonList", new { companyId = CompanyId });
        }


        [HttpPost]
        
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(OfficerAssignViewModel vm)
        {
            bool result = false;
            int companyId = Convert.ToInt32(Session["CompanyId"]);
            if (vm.OfficerAssign.OfficerAssignId <= 0)
            {
                result = officerAssignService.SaveOfficerAssign(0, vm.OfficerAssign);
            }
            else
            {
                result = officerAssignService.SaveOfficerAssign(vm.OfficerAssign.OfficerAssignId, vm.OfficerAssign);
            }
            if (result)
            {
                TempData["message"] = "Marketing Officer Assigned Successfully";
            }
            return RedirectToAction("Index", new { companyId });
        }


        [HttpGet]
        
        public ActionResult DeleteOfficerAssign(int id)
        {
            int companyId = Convert.ToInt32(Session["CompanyId"]);
            bool result = officerAssignService.DeleteOfficerAssign(id);
            if (result)
            {
                TempData["message"] = "Marketing Officer Deleted Successfully";
                return RedirectToAction("Index", new { companyId });
            }
            return View();
        }

        [HttpPost]
        public JsonResult GetMarketingOfficersByCustomerZone(int customerId)
        {
            List<LongSelectModel> marketingOfficers = officerAssignService.GetMarketingOfficersByCustomerZone(customerId);
            return Json(marketingOfficers, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult GetOfficerSelectModelsByZone(int zoneId)
        {
            List<SelectModel> officers = officerAssignService.GetOfficerSelectModelsByZone(zoneId);
            return Json(officers, JsonRequestBehavior.AllowGet);
        }


        //[HttpPost]
        //
        //public ActionResult CreateOrEdit(List<UpazilaAssignModel> upazilaAssigns)
        //{
        //    bool result = upazilaAssignService.SaveUpazilaAssign(upazilaAssigns);
        //    if (result)
        //    {
        //        TempData["message"] = "Operation Successful !";
        //    }
        //    return RedirectToAction("Index");
        //}

        //[HttpGet]
        //public PartialViewResult GetUpazilaListByDistrict(int districtId, long employeeId)
        //{
        //    List<UpazilaAssignModel> upazilaAssigns = upazilaAssignService.GetUpazilaListByDistrictAndEmployee(districtId, employeeId);
        //    return PartialView("~/Views/UpazilaAssign/_upazilaList.cshtml", upazilaAssigns);
        //}

    }
}

Source/KGERP/Views/OfficerAssign/Create.cshtml
@model KGERP.Service.ServiceModel.OfficerAssignModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="border-bottom:5px solid red;">
    <h3>Marketing Officer Assign</h3>
</div>


<form method="Post">
    <div class="col-md-12 " style="margin-top:30px;">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row" style="margin-left:8px;">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Zone</label>

                    <select id="zonevalue" class="form-control" name="ZoneId" asp-for="ZoneId">
                    <option  value="">--Select Zone--</option>
                    @foreach (var g in Model.ZoneList)
                    {
                        <option value="@g.Value">@g.Text</option>
                    }
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <div class="form-group row" style="margin-left:8px;">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Sub Zone</label>
                        <select id="Subzonevalue" class="form-control" name="subZoneId" asp-for="subZoneId">
                            <option value="">--Select Sub Zone--</option>
                           
                        </select>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-12 " >
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Marketing Person</label>
                    <div class="col-sm-10">
                        <input type="text" autocomplete="on"  class="form-control" id="employee" placeholder="Marketing Person">
                        <input hidden name="EmpId" id="EmpId" />
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Remarks</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="Remarks" asp-for="Remarks" id="rmks" placeholder="Remarks">
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-12 " >
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Start Date</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control" asp-for="StartDate" name="StartDate" id="inputEmail3" >

                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="inputEmail3"  class="col-sm-2 col-form-label">End Date</label>
                        <div class="col-sm-10">
                            <input type="date" class="form-control" name="EndDate" asp-for="EndDate" id="inputEmail3" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="text-center " >
        <input style="margin-top:40px;" type="submit" class="btn btn-primary pull-right" value="Save" />
    </div>
    


</form> 





@section Scripts
{
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
<script type="text/javascript">



        $(function () {
            $("#employee").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '/Employee/EmployeeAutoCompleteOfficerJoin/',
                        //data: "{ 'prefix': '" + request.term + "'}",
                        data: '{"prefix":"' + request.term + '", "productType":"F","CompanyId":@Model.CompanyId}',
                        dataType: "json",
                        type: "POST",
                        cache: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            //alert(response.responseText);
                        },
                        failure: function (response) {
                            //alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#EmpId").val(i.item.val);
                },
                minLength: 1,
                cache: true

            }).focus(function () {
                $(this).autocomplete("search");
            });
        });

        $("#zonevalue").change(function () {
            var ZoneinfoId = $('#zonevalue').find(":selected").val();
            $.ajax({
                type: "Get",
                url: "@Url.Action("GetSubZone", "OfficerAssign")",
                datatype: "Json",
                data: { Id: ZoneinfoId },
                success: function (data) {
                    console.log(data);
                    var select = $("#Subzonevalue");
                    select.children().remove();
                    select.append($("<option>").val('').text('Select SubZone'));
                    $(data.SubZoneList).each(function (index, item) {
                        select.append($("<option data-toggle='tooltip' title='" + item.Value + "'>").val(item.Value).text(item.Text));
                    });
                    return false;
                    }
                });


        });
</script>

    }

Source/KGERP/Views/OfficerAssign/CreateOrEdit.cshtml
@model KGERP.ViewModel.OfficerAssignViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.OfficerAssign.OfficerAssignId)
    @Html.HiddenFor(x => x.OfficerAssign.CompanyId)

<div class="form-horizontal">
    <h4>Marketing Officer Assign</h4>
    <hr style="border-color:#ff0000; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.OfficerAssign.ZoneId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.OfficerAssign.ZoneId, new SelectList(Model.Zones, "Value", "Text"), "--Select--", htmlAttributes: new { @class = "dropdownsize form-control", @id = "ddlDistrict", @onchange = "getUpazilaCode()" })
            @Html.ValidationMessageFor(model => model.OfficerAssign.ZoneId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OfficerAssign.EmpId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OfficerAssign.OfficerName, new { htmlAttributes = new { @class = "form-control", @name = "employee", @id = "employee" } })
            @Html.HiddenFor(x => x.OfficerAssign.EmpId, new { @id = "employeeId", @name = "employeeId" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.OfficerAssign.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-8">
            @Html.EditorFor(model => model.OfficerAssign.StartDate, new { htmlAttributes = new { @class = "datepicker", @style = "width:240px", @placeholder = "dd/mm/yyyy", @autocomplete = "off" } })
            @Html.ValidationMessageFor(model => model.OfficerAssign.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OfficerAssign.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-8">
            @Html.EditorFor(model => model.OfficerAssign.EndDate, new { htmlAttributes = new { @class = "datepicker", @style = "width:240px", @placeholder = "dd/mm/yyyy", @autocomplete = "off" } })
            @Html.ValidationMessageFor(model => model.OfficerAssign.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.OfficerAssign.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-8">
            @Html.TextAreaFor(model => model.OfficerAssign.Remarks, 2, 51, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.OfficerAssign.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.OfficerAssign.IsActive)
                @Html.ValidationMessageFor(model => model.OfficerAssign.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col-md-offset-3 col-md-3">
        <div class="form-group">
            <a href="@Url.Action("Index",new {companyId=Model.OfficerAssign.CompanyId })" class="btn btn-danger">
                <span class="glyphicon glyphicon-remove-circle"></span>   Close
            </a>
            <button type="submit" class="btn btn-primary" onclick="javascript: return SubmitForm();" style="margin-left: 20px;"><span class="glyphicon glyphicon-floppy-disk"></span>Submit</button>
        </div>
    </div>
</div>
}


@section Scripts
{
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <script type="text/javascript">

        function SubmitForm() {

            var r = confirm("Are you sure you want to submit?");
            if (r == false) {
                return false;
            }
        }

        $(function () {
            $("#employee").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '/Employee/EmployeeAutoComplete/',
                        //data: "{ 'prefix': '" + request.term + "'}",
                        data: '{"prefix":"' + request.term + '", "productType":"F"}',
                        dataType: "json",
                        type: "POST",
                        cache: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            //alert(response.responseText);
                        },
                        failure: function (response) {
                            //alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#employeeId").val(i.item.val);
                },
                minLength: 1,
                cache: true

            }).focus(function () {
                $(this).autocomplete("search");
            });
        });

    </script>

}

Source/KGERP/Views/OfficerAssign/Delete.cshtml
@model KGERP.Service.ServiceModel.DistrictModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>District</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Source/KGERP/Views/OfficerAssign/EditMarketingOfficer.cshtml
@model KGERP.Service.ServiceModel.OfficerAssignModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<form method="Post">
    <div class="col-md-12 " style="margin-top:30px;">
        <div class="row">
            <div class="col-md-6">
                <input name="OfficerAssignId" value="@Model.officervm.OfficerAssignId" hidden />
                <div class="form-group row" style="margin-left:8px;">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Zone</label>
                    <select id="zonevalue"  class="form-control" name="ZoneId">
                        <option value="0">---Select Zone  --- </option>
                        @{
                            foreach (var item in Model.ZoneList2)
                            {
                                if (item.Value == Model.ZoneId)
                                {
                                    <option value="@item.Value" selected>@item.Text</option>
                                }
                                else
                                {
                                    <option value="@item.Value">@item.Text</option>
                                }
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <div class="form-group row" style="margin-left:8px;">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">SubZone</label>
                        <select id="Subzonevalue" class="form-control" name="subZoneId">
                            <option value="0">---Select SubZone  --- </option>
                            @{
                                foreach (var item in Model.SubZoneList2)
                                {
                                    if (item.Value == Model.officervm.SubZoneId)
                                    {
                                        <option value="@item.Value" selected>@item.Text</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-12 ">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Marketing Person</label>
                    <div class="col-sm-10">
                        <input type="text" value="@Model.officervm.EmployeeName"readonly class="form-control" id="employee" placeholder="Marketing Person">
                        <input hidden value="@Model.officervm.EmpId" name="EmpId" id="EmpId" />
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Remarks</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" value="@Model.officervm.Remarks" name="Remarks" asp-for="Remarks" id="rmks" placeholder="Remarks">
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="col-md-12 ">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Start Date</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control" value="@Model.officervm.StartDate" name="StartDate" id="StartDate">*
                        @*@Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "datepickeronPage" } })
                        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })*@
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">End Date</label>
                        <div class="col-sm-10">
                            <input type="datetime-local" class="form-control" value="@Model.officervm.EndDate" name="EndDate" asp-for="EndDate" id="inputEmail3" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="text-center ">
        <input style="margin-top:40px;" type="submit" class="btn btn-primary" value="save" />
    </div>



</form>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
<script type="text/javascript">
    //$(document).ready(function () {
    //    $('.datepickeronPage').datepicker({
    //        dateFormat: 'dd-M-yy',
    //        showOn: 'both',
    //        buttonText: "<i class='fa fa-calendar'></i>",
    //        changeMonth: true,
    //        changeYear: true,
    //        yearRange: "1950:+150"
    //    });
    //    });
    $("#zonevalue").change(function () {
            var ZoneinfoId = $('#zonevalue').find(":selected").val();
            $.ajax({
                type: "Get",
                url: "@Url.Action("GetSubZone", "OfficerAssign")",
                datatype: "Json",
                data: { Id: ZoneinfoId },
                success: function (data) {
                    console.log(data);
                    var select = $("#Subzonevalue");
                    select.children().remove();
                    select.append($("<option>").val('').text('Select SubZone'));
                    $(data.SubZoneList).each(function (index, item) {
                        select.append($("<option data-toggle='tooltip' title='" + item.Value + "'>").val(item.Value).text(item.Text));
                    });
                    return false;
                    }
                });


        });


</script>
}

Source/KGERP/Views/OfficerAssign/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<KGERP.Service.ServiceModel.OfficerAssignModel>
@using PagedList;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var message = TempData["message"];
}
<link href="~/Content/CustomCss/search-form.css" rel="stylesheet" />



<div class="row">
    <div class="col-md-6">
        <span style="font-size:20px;font-family:Arial"><b>Zone Wise Marketing Officers List</b></span>
    </div>
    <div class="col-md-4">
        @using (Html.BeginForm("Index", "OfficerAssign", FormMethod.Get, new { @class = "example" }))
        {
            <input type="hidden" value="@Request.QueryString["companyId"]" name="companyId" />
            <input type="text" placeholder="Search.." autocomplete="off" name="searchText">
            <button type="submit"><i class="fa fa-search"></i></button>

        }
    </div>

    <div class="col-md-2">
        <a href="@Url.Action("CreateOrEdit",new { id=0 })" class="btn btn-primary pull-right">
            <span class="glyphicon glyphicon-plus-sign"></span> Add Marketing Officer
        </a>
    </div>
</div>


<div class="row">
    <hr style="border-color:#ff0000; padding:0px;margin-top: 5px;margin-bottom: 5px; border-width: 2px;" />
    <table class="table table-striped">
        <tr style="background-color:#4CAF50;color:#FFFFFF">
            <th>
                SL
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().ZoneId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().EmpId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Remarks)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().IsActive)
            </th>
            <th class="text-center">Action</th>
        </tr>

        @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
        {
            <tr>
                <td>
                    @((item.Index + 1) + (Model.PageNumber - 1) * Model.PageSize)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Zone.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Employee.Name)
                </td>

                <td>
                    @if (item.Data.StartDate.HasValue)
                    {
                        @item.Data.StartDate.Value.ToString("dd MMM yyyy")
                    }
                </td>
                <td>
                    @if (item.Data.EndDate.HasValue)
                    {
                        @item.Data.EndDate.Value.ToString("dd MMM yyyy")
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.Remarks)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.IsActive)
                </td>
                <td class="text-center">
                    <a href="@Url.Action("CreateOrEdit", new {id = item.Data.OfficerAssignId})" title="Edit" class="btn btn-info btn-xs">
                        <i class="fa fa-edit" style="font-size:15px;" aria-hidden="true"></i>
                    </a>
                    <a href="@Url.Action("DeleteOfficerAssign", new { id = item.Data.OfficerAssignId})" title="Delete" onclick="return confirm('Are you sure to delete this ?');" class="btn btn-danger btn-xs">
                        <i class="fa fa-trash" style="font-size:15px;" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        }

    </table>
    @if (Model.PageCount > 1)
    {
        <span class="btn btn-success" style="margin-top:-10px">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        </span>
        <span class="checkbox" style="margin-top:-10px">
            @Html.PagedListPager(Model, Page_No => Url.Action("Index", "OfficerAssign",
                                                             new { companyId = Request.QueryString["companyId"], Page_No, Sorting_Order = Request.QueryString["Search"], SearchText = Request.QueryString["searchText"] }))
        </span>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">
        var message = '@message';
        if(message){
            alert(message);
        }
    </script>

}