Source/KGERP/Controllers/DemandController.cs
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using KGERP.ViewModel;
using PagedList;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [CheckSession]
    public class DemandController : BaseController
    {

        private readonly IDemandService demandService;
        private readonly IVendorService vendorService;
        private readonly IProductCategoryService productCategoryService;
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public DemandController(IDemandService demandService,
            IVendorService vendorService,
            IProductCategoryService productCategoryService)
        {
            this.demandService = demandService;
            this.vendorService = vendorService;
            this.productCategoryService = productCategoryService;
        }

        
        [HttpGet]
        public async Task<ActionResult> Index(int companyId,  DateTime? fromDate, DateTime? toDate)
        {
            if (companyId > 0)
            {
                Session["CompanyId"] = companyId;
            }
            if (fromDate == null)
            {
                fromDate = DateTime.Now.AddMonths(-2);
            }
            if (toDate == null)
            {
                toDate = DateTime.Now;
            }
            DemandModel demandModel = new DemandModel();

            demandModel = await demandService.GetDemandList(companyId, fromDate, toDate);

            demandModel.StrFromDate = fromDate.Value.ToString("yyyy-MM-dd");
            demandModel.StrToDate = toDate.Value.ToString("yyyy-MM-dd");
           
            return View(demandModel);
        }

        [HttpPost]
        
        public async Task<ActionResult> Index(DemandModel model)
        {
            if (model.CompanyId > 0)
            {
                Session["CompanyId"] = model.CompanyId;
            }
            model.FromDate = Convert.ToDateTime(model.StrFromDate);
            model.ToDate = Convert.ToDateTime(model.StrToDate);
            return RedirectToAction(nameof(Index), new { companyId = model.CompanyId, fromDate = model.FromDate, toDate = model.ToDate });
        }

        
        [HttpGet]
        public ActionResult CreateOrEdit(long id)
        {
            DemandModel demand = demandService.GetDemand(id);
            return View(demand);
        }


        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(DemandModel model)
        {
            bool result = false;
            string message = string.Empty;
            if (model.DemandId <= 0)
            {
                model.RequisitionType = 2;
                result = demandService.SaveDemand(0, model, out message);
            }
            else
            {
                result = demandService.SaveDemand(model.DemandId, model, out message);

            }
            TempData["successMessage"] = message;
            if (result)
            {
                TempData["successMessage"] = "Demand Created Successfully !";
                return RedirectToAction("Index", new { companyId = model.CompanyId });
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult GetNewDemandNo(string strDemandDate)
        {
            string demandNo = demandService.GetNewDemandNo(strDemandDate);
            return Json(demandNo, JsonRequestBehavior.AllowGet);
        }
        //
        //[HttpGet]
        //public ActionResult GetStoreProduct(int? Page_No, string searchText)
        //{
        //    searchText = searchText == null ? "" : searchText;
        //    List<SoreProductQty> result = storeService.GetStoreProductQty().Where(x => x.ProductName.ToLower().Contains(searchText.ToLower()) || x.StoreName.ToLower().Contains(searchText.ToLower())).ToList();
        //    //return View(result);
        //    int Size_Of_Page = 10;
        //    int No_Of_Page = (Page_No ?? 1);
        //    return View(result.ToPagedList(No_Of_Page, Size_Of_Page));
        //}


        
        [HttpGet]
        public ActionResult DemandItemIndex(long demandId)
        {
            DemandViewModel vm = new DemandViewModel();
            try
            {
                vm.Demand = demandService.GetDemand(demandId);
                vm.DemandItems = demandService.GetDemandItems(demandId);
                vm.DemandItemDetails = demandService.GetDemandItemDetails(demandId);
                return View(vm);
            }
            catch (Exception ex)
            {
                logger.Error(ex);
                return View(vm);
            }
        }
    }
}

Source/KGERP/Controllers/ProductBookingController.cs
using DocumentFormat.OpenXml.Drawing.Charts;
using DocumentFormat.OpenXml.VariantTypes;
using KGERP.Data.Models;
using KGERP.Service.Configuration;
using KGERP.Service.Implementation;
using KGERP.Service.Implementation.FTP;
using KGERP.Service.Implementation.Realestate;
using KGERP.Service.Implementation.Realestate.BookingAprovalList;
using KGERP.Service.Implementation.Realestate.BookingCollaction;
using KGERP.Service.Implementation.Realestate.CustomersBooking;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Service.ServiceModel.FTP_Models;
using KGERP.Services.Procurement;
using KGERP.Utility;
using KGERP.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Linq.Dynamic;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Services.Description;
using static KGERP.Controllers.Custom_Authorization.ParentAuthorizedAttribute;

namespace KGERP.Controllers
{
    [CheckSession]
    public class ProductBookingController : Controller
    {

        private ERPEntities db = new ERPEntities();
        private readonly ConfigurationService _coservice;
        IKgReCrmService kgReCrmService = new KgReCrmService();
        private readonly IVoucherTypeService voucherTypeService;
        private readonly ICostHeadsService _costHeadService;
        private IFTPService _ftpservice;
        private readonly IVendorService _vendorService;
        private readonly IInstallmentTypeService _Service;
        private readonly IGLDLCustomerService gLDLCustomerService;
        private readonly ICustomerBookingService customerBookingService;
        private readonly IBookingInstallmentService bookingInstallmentService;
        private readonly IBookingAprovalStatus bookingAprovalStatus;
        private readonly ITeamService _teamService;
        private readonly ICompanyService _companyService;
        private readonly IBookingCollaction _bookingCollaction;
        private readonly AccountingService _accountingService;
        string constr = ConfigurationManager.ConnectionStrings["DBConnectionString"].ConnectionString;
        public ProductBookingController(IBookingInstallmentService bookingInstallmentService,
            ICustomerBookingService customerBookingService,
            IGLDLCustomerService gLDLCustomerService,
            IVoucherTypeService voucherTypeService,
            ICostHeadsService costHeadService,
            IFTPService ftpservice,
            IBookingAprovalStatus bookingAprovalStatus,
            ITeamService teamService,
            AccountingService accountingService,
            IInstallmentTypeService _Service,
            ICompanyService _companyService,
            IBookingCollaction bookingCollaction,
            IVendorService vendorService,
            ConfigurationService coservice)
        {
            this.voucherTypeService = voucherTypeService;
            this._ftpservice = ftpservice;
            this._Service = _Service;
            this._companyService = _companyService;
            this.bookingAprovalStatus = bookingAprovalStatus;
            this.customerBookingService = customerBookingService;
            this.gLDLCustomerService = gLDLCustomerService;
            this.bookingInstallmentService = bookingInstallmentService;
            _costHeadService = costHeadService;
            _teamService = teamService;
            _accountingService = accountingService;
            _bookingCollaction = bookingCollaction;
            _vendorService = vendorService;
           this._coservice = coservice;
        }
        public async Task<ActionResult> KPLCustomer(int companyId)
        {
            VMCommonSupplier vmCommonCustomer = new VMCommonSupplier();
            vmCommonCustomer = await Task.Run(() => kgReCrmService.GetCustomer(companyId));
           

            return View(vmCommonCustomer);
        }


        // GET: ProductBooking
        #region //GLDLNEW   

       
        [HttpPost]
        public JsonResult GetByProduct(int productid)
        {
            var result = kgReCrmService.Getbyproduct(productid);
            return Json(result);
        }


        [HttpGet]
        public JsonResult GetByProductstastus(int productid)
        {
            GLDLBookingViewModel vm = new GLDLBookingViewModel();
            var result = kgReCrmService.Getbyproduct(productid);
            vm.ProductId = result.ProductId;
            if (result.CompanyId==7)
            {
                vm.PStatus = ((ProductStatusEnumGLDL)result.Status).ToString();
            }
            else
            {
                vm.PStatus = ((ProductStatusEnumKPL)result.Status).ToString();
            }
            
            return Json(vm,JsonRequestBehavior.AllowGet);
        }
       
        [HttpPost]
        public async Task<JsonResult> GetProductCostHeadsbyId(int productid, int companyId)
        {
            BookingViewModel model = new BookingViewModel();
            model.product = kgReCrmService.GetbyproductForGldl(productid);
            return Json(model);
        }
           
       
        [HttpGet]
        public JsonResult GetfileCheck(int companyId, string fileNo)
        {
            GLDLBookingViewModel vm = new GLDLBookingViewModel();
            var res = gLDLCustomerService.bookingFilecheck(companyId, fileNo);
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ActionResult> CustomerBooking(int companyId, int vandorId = 0)
        {
            GLDLBookingViewModel vm = new GLDLBookingViewModel() { CompanyId = companyId };
            vm.ApplicationDate = DateTime.Now;
            vm.ApplicationDateString = DateTime.Now.ToString("dd-MMM-yyyy");
            vm.DownPaymentDateNew = DateTime.Now.ToString("dd-MMM-yyyy");
            vm.BookingMoneyPaymentDateNew = DateTime.Now.ToString("dd-MMM-yyyy");
            if (vandorId > 0)
            {
                var crm = kgReCrmService.GetVendorById(vandorId);
               // vm.CustomerGroupName = crm.Name + " & Associated";
                vm.CustomerGroupName = crm.Name;
                vm.PrimaryContactAddr = crm.Address;
                vm.PrimaryContactNo = crm.Phone;
                vm.PrimaryEmail = crm.Email;
            }          
            vm.ProductCategoryList = voucherTypeService.GetProductCategoryGldl(companyId);
            vm.LstPurchaseCostHeads = await _costHeadService.GetCostHeadsByCompanyId(companyId);
            vm.BookingInstallmentType = await _costHeadService.GetCompanyBookingInstallmentType(companyId);
            vm.Employee = new SelectList(_teamService.GetTeamListByCompanyId(companyId), "Value", "Text");            
            return View(vm);
        }
        [HttpPost]
        public async Task<ActionResult> CustomerBooking(GLDLBookingViewModel model)
        {
            model.EntryBy = Convert.ToInt32(Session["Id"]);
            model.ApplicationDate = Convert.ToDateTime(model.ApplicationDateString);
            model.BookingDate = Convert.ToDateTime(model.BookingDateString);
            model.DownPaymentDate = Convert.ToDateTime(model.DownPaymentDateNew);
            model.BookingMoneyPaymentDate = Convert.ToDateTime(model.BookingMoneyPaymentDateNew);
            int count = await gLDLCustomerService.GetByclient(model.ClientId);
            model.ClientName = model.CustomerGroupName;
            if (count == 0)
            {
                model.CustomerGroupName = model.CustomerGroupName + "(" + "#001" + ")";
            }
            else
            {
                model.CustomerGroupName = model.CustomerGroupName + "(" + "#00" + (count + 1) + ")";
            }
            var result = await gLDLCustomerService.CustomerBokking(model);
            if (result.CGId != 0)
            {
                return RedirectToAction("CustomerBookingInformation", new { companyId = model.CompanyId, CGId = model.CGId });
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CustomerBookingPassUrl(GLDLBookingViewModel model)
        {
            return RedirectToAction("CustomerBooking", new { clientId = model.ClientId, companyId = model.CompanyId });
        }

        

        [HttpGet]
        public async Task<ActionResult> CustomerBookingInformation(int companyId, long CGId)
        {
            var res = await customerBookingService.CustomerBookingView(companyId, CGId);
            res.pRM_Relations = await customerBookingService.PRMRelation();
            res.BookingInstallmentType = await _costHeadService.GetCompanyBookingInstallmentType(companyId);
            var MapEmployeeId = Convert.ToInt32(Session["Id"]);

            if (res.EmployeeId == MapEmployeeId && res.approval.EntryBy > 0 && res.approval.CheckedBy > 0 && res.approval.ApprovedBy > 0)
            {
                res.IsShow = true;
            }
            else
            {
                res.IsShow = false;
            }
            return View(res);
        }
        [HttpGet]
        public async Task<ActionResult> UpdateBookingInformation(int companyId, long CGId)
        {
            var res = await customerBookingService.CustomerBookingView(companyId, CGId);
            res.ApplicationDateString = res.ApplicationDate?.ToString("dd-MMM-yyyy");
            res.BookingDateString = res.BookingDate?.ToString("dd-MMM-yyyy");
            res.Employee = new SelectList(_teamService.GetTeamListByCompanyId(companyId), "Value", "Text");
            return View(res);
        }
        [HttpPost]
        public async Task<ActionResult> UpdateBookingInformation(GLDLBookingViewModel model)
        {
            model.ApplicationDate = Convert.ToDateTime(model.ApplicationDateString);
            model.BookingDate = Convert.ToDateTime(model.BookingDateString);

Source/KGERP/Views/ProductBooking/BookingRecheckList.cshtml
@model KGERP.Service.ServiceModel.GLDLBookingViewModel
@{
    ViewBag.Title = "CustomerBookingList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }

    .ui-front {
        z-index: 2100 !important;
    }

    .ui-datepicker {
        z-index: 2100 !important;
    }

    @@media (min-width: 768px) {
        .modal-content {
            width: 750px;
        }
    }

    .input-group {
        width: 100% !important;
    }

    .mb-2 {
        margin-bottom: 15px !important;
    }

    .input-group .form-control {
        max-width: 100%;
    }

    .badge-primary {
        color: #fff;
        background-color: #007bff;
    }

    .badge-success {
        color: #fff;
        background-color: #28a745;
    }

    .badge-danger {
        color: #fff;
        background-color: #dc3545;
    }

    .badge-dark {
        color: #fff;
        background-color: #343a40;
    }

    .badge-info {
        color: #fff;
        background-color: #17a2b8;
    }

    .content-header {
        position: relative;
        padding: 0px 15px 20px 5px;
        background-color: #4caf5029 !important;
    }
</style>
<section class="content-header" style="margin-bottom:20px">
    <div class="row">
        <div class="col-sm-4">
            <h3>
                Customer Booking List
            </h3>
        </div>
        @*<div class="col-sm-8" style="margin-top:29px;">
            @using (Html.BeginForm("CustomerBookingPassUrl", "ProductBooking", FormMethod.Post))
            {
                @Html.HiddenFor(m => m.CompanyId, new { @id = "companyId" })
                <div style="width:100%" class="row">
                    @Html.Label("Select Client :", htmlAttributes: new { @class = " col-md-2 control-label" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @class = "form-control", @name = "ClientName", @id = "ClientNameId" } })
                        @Html.HiddenFor(x => x.ClientId, new { @id = "BookingBy", @name = "ClientId" })
                        @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-sm-3">
                        <input id="submit" type="submit" data-confirm="Are you sure to submit?" value="New Booking" class="btn btn-success pull-right" />
                    </div>
                </div>
            }
        </div>*@
    </div>
</section>
<div class="table-responsive col-md-12">
    <table id="KgErpDataTable" style="width:100%; background-color:#ddd;" class="table table-striped">
        <thead>
            <tr>
                <th>SL</th>
                <th>Customer Group Name</th>
                <th>Project Name</th>
                <th>Block Name</th>
                <th>Plot Name</th>
                <th>Plot Size</th>
                <th>Booking Money</th>
                <th>Land Value</th>
                <th>Rest of Amount</th>
                <th>Steps</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        @{int sl = 0;
        }
        <tbody>
            @foreach (var item in Model.datalist)
            {
                <tr>
                    <td>@(++sl)</td>
                    <td>@item.CustomerGroupName</td>
                    <td>@item.ProjectName</td>
                    <td>@item.BlockName</td>
                    <td>@item.PlotName</td>
                    <td>@item.PlotSize</td>
                    <td>@item.BookingMoney</td>
                    <td>@item.LandValue</td>
                    <td>@item.RestofAmount</td>
                    <td>
                        @if (item.Step == 1)
                        {
                            <span class="badge badge-primary">Dealing officer</span>
                        }
                        @if (item.Step == 2)
                        {
                            <span class="badge badge-dark" data-toggle="modal" data-target="#exampleModal" onclick="statusevent(@item.BookingId, '@item.CGId')">Head of sales</span>
                        }
                        @if (item.Step == 3)
                        {
                            <span class="badge badge-success"> DMD approval</span>
                        }
                        @if (item.Step == 4)
                        {
                            <span class="badge badge-success"> MD approval</span>
                        }
                    </td>
                    <td>
                        @if (item.Status == 1)
                        {
                            <span class="badge badge-primary">Draft</span>
                        }
                        @if (item.Status == 2)
                        {
                            <span class="badge badge-dark">Recheck</span>
                        }
                        @if (item.Status == 3)
                        {
                            <span class="badge badge-success">Approve</span>
                        }
                        @if (item.Status == 4)
                        {
                            <span class="badge badge-danger">Reject</span>
                        }
                    </td>
                    <td>
                        <a href="/ProductBooking/CustomerBookingInformation?companyId=@item.CompanyId&CGId=@item.CGId" target="_blank" class="btn btn-warning btn-xs">
                            Details
                        </a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"> Change Booking Status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("RechecekBookingStatus", "ProductBooking", FormMethod.Post))
            {
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(x => x.CompanyId, new { @id = "CompanyId" })
                    @Html.HiddenFor(x => x.CGId, new { @id = "CGId" })
                    @Html.HiddenFor(x => x.BookingId, new { @id = "BookingId" })

                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Select Status</label>
                        <select class="form-control" name="Status" id="Status">
                            <option value="3">Approve</option>
                            <option value="4">Reject</option>
                        </select>
                    </div>


                    <div class="modal-footer">
                        <input id="submit" type="submit" data-confirm="Are you sure to submit?" value="Submit" class="btn btn-success pull-right" />
                        <a @*href="@Url.Action("Index","Demand",new { companyId=Model.CompanyId})"*@ data-dismiss="modal" class="btn btn-danger pull-right" style="margin-right:15px">
                            Close <i class="fa fa-close" aria-hidden="true"></i>
                        </a>
                    </div>

                </div>
            }
        </div>
    </div>
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">
        $(function () {
            $("#ClientNameId").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '/ProductBooking/CustomerAutoComplete/',
                        //data: "{ 'prefix': '" + request.term + "'}",
                        data: '{"prefix":"' + request.term + '", "companyId":"' +@Model.CompanyId+'"}',
                        dataType: "json",
                        type: "POST",
                        cache: true,
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#BookingBy").val(i.item.val);
                },
                minLength: 1,
                cache: true

            }).focus(function () {
                $(this).autocomplete("search");
            });
        });

        function statusevent(bookinid, cgid) {
            $("#CGId").val(cgid);
            $("#BookingId").val(bookinid);
        }

    </script>
}

Source/KGERP/Views/ProductBooking/KPLCustomer.cshtml
@{
    ViewData["Title"] = "Dealer / Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@model KGERP.Service.Configuration.VMCommonSupplier

<style type="text/css">

    input, select, textarea {
        max-width: 100%;
    }
</style>

<section class="content-header">
    <h1>
        Dealer / Customer
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li class="active">Dealer / Customer</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="box-danger">

                    <!-- /.box-header -->

                    <div class="box-footer">
                    </div>
                    <div class="box">
                        <div class="box-danger">
                            <div class="box-header">

                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="table-responsive text-nowrap">
                                    <table id="KgErpDataTable" class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>SL</th>
                                                <th>Code</th>
                                                <th>

                                                    Name
                                                </th>
                                               
                                                <th>
                                                    Phone
                                                </th>
                                                <th>
                                                    Email
                                                </th>
                                               
                                                <th>
                                                    Zone
                                                </th>

                                               
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        @{int sl = 0;
                                        }
                                        <tbody>
                                            @foreach (var item in Model.DataList)
                                            {
                                                <tr>
                                                    <td>@(++sl)</td>
                                                    <td>
                                                        @item.Code
                                                    </td>
                                                    <td>
                                                        @item.Name

                                                    </td>
                                                   
                                                    <td>
                                                        @item.Phone
                                                    </td>
                                                    <td>
                                                        @item.Email
                                                    </td>
                                                  
                                                    <td>
                                                        @item.ZoneName 
                                                    </td>
                                                   
                                                    <td>
                                                        <a id="@item.ID" onclick="makeEditble(@item.ID);" class="linkPointer" title="Edit"><i class="fa fa-pencil-square-o"></i></a>
                                                        <a id="@item.ID" onclick="makeDeletable(@item.ID);" class="linkPointer" data-toggle="modal" data-target="#deleteModal" title="Delete"
                                                           data-placement="top">
                                                            <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                                                        </a>

                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>




                            </div>
                            <div class="box-footer">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</section>



@section scripts {

    <script type="text/javascript">


        $(document).ready(function () {
            $('.formValidator').bootstrapValidator();


        });
       

    </script>
}