Source/KGERP/Controllers/KttlServicesController.cs
using KGERP.Data.Models;
using KGERP.Service.Implementation;
using KGERP.Service.Interface;
using KGERP.Service.ServiceModel;
using KGERP.Utility;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace KGERP.Controllers
{
    [CheckSession]
    public class KttlServicesController : Controller
    {
        private ERPEntities db = new ERPEntities();
        IKttlService kttlService = new KttlServiceService();
        IKttlCustomerService kttlCustomerService = new KttlCustomerService();
        IDropDownItemService dropDownItemService = new DropDownItemService(new ERPEntities());

        // GET: KttlServices
        public ActionResult Index(int? Page_No, string searchText)
        {
            //return View(db.KttlServices.ToList());
            searchText = searchText ?? "";
            List<KttlServiceModel> kttlServices = kttlService.GetKttlServices(searchText);
            int Size_Of_Page = 10;
            int No_Of_Page = (Page_No ?? 1);
            return View(kttlServices.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        // GET: KttlServices/Details/5
        public ActionResult Details(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            KttlServiceModel kttlServices = kttlService.GetKttlService(id);
            // KttlService kttlService = db.KttlServices.Find(id);

            if (kttlServices == null)
            {
                return HttpNotFound();
            }
            return View(kttlServices);
        }

        // GET: KttlServices/Create
        public ActionResult Create(string clientId, int id, string searchText)
        {

            Session["FullName"] = string.Empty;
            Session["ClientId"] = string.Empty;
            //Session["Id"] = 0;
            string clientInfo = string.Empty;

            KttlCustomer kttlCustomer = db.KttlCustomers.Find(id);
            if (kttlCustomer != null)
            {
                ViewBag.FullName = kttlCustomer.FullName;
                Session["ClientId"] = kttlCustomer.ClientId;
            }

            KttlServiceModel model = new KttlServiceModel();
            model = kttlService.GetKttlService(id);

            if (model == null)
            {
                model = new KttlServiceModel();
                model.ServiceTypes = dropDownItemService.GetDropDownItemSelectModels(16);
            }
            else
            {
                model.ServiceTypes = dropDownItemService.GetDropDownItemSelectModels(16);
            }

            return View(model);
        }

        
        [HttpGet]
        public ActionResult CreateOrEdit(int? clientId, int? id, string searchText, string companyId)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == "KG3068" || System.Web.HttpContext.Current.User.Identity.Name == "KG1223"
                 || System.Web.HttpContext.Current.User.Identity.Name == "KG0284" || System.Web.HttpContext.Current.User.Identity.Name == "KG1088"
                 || System.Web.HttpContext.Current.User.Identity.Name == "KG0129" || System.Web.HttpContext.Current.User.Identity.Name == "KG0286")
            {
                Session["FullName"] = string.Empty;
                Session["ClientId"] = string.Empty;
                //Session["Id"] = 0;
                string clientInfo = string.Empty;
                KttlCustomer _KttlCustomer = null;
                KttlCustomer _KttlCustomer2 = null;

                if (clientId > 0)
                {
                    _KttlCustomer = db.KttlCustomers.Where(x => x.ClientId == clientId).FirstOrDefault();
                }

                if (!string.IsNullOrEmpty(searchText))
                {
                    int searchText1 = Convert.ToInt32(searchText);
                    _KttlCustomer2 = db.KttlCustomers.Where(x => x.ClientId.Equals(searchText1)).FirstOrDefault();

                }
                KttlService _KttlServece = db.KttlServices.Find(id);
                if (_KttlCustomer2 != null)
                {
                    Session["FullName"] = _KttlCustomer2.FullName;
                    Session["ClientId"] = _KttlCustomer2.ClientId;
                    // Session["Id"] = _KttlCustomer2.ClientId;
                    clientInfo = GetKTTLClientInformation(_KttlCustomer2.ClientId);
                }

                if (_KttlCustomer != null)
                {
                    Session["ClientId"] = string.Empty;
                    Session["FullName"] = string.Empty;
                    ViewBag.FullName = _KttlCustomer.FullName;
                    ViewBag.ClientId = _KttlCustomer.ClientId;
                    //ViewBag.Id = _KttlCustomer.ClientId;
                    Session["ClientId"] = _KttlCustomer.ClientId;
                    Session["FullName"] = _KttlCustomer.FullName;
                    clientInfo = GetKTTLClientInformation(_KttlCustomer.ClientId);
                }
                if (_KttlServece != null)
                {
                    Session["OID"] = _KttlServece.OID;
                }

                KttlServiceModel model = new KttlServiceModel();
                model = kttlService.GetKttlService(Convert.ToInt32(id));


                if (model == null)
                {
                    model = new KttlServiceModel();
                    model.ServiceTypes = dropDownItemService.GetDropDownItemSelectModels(16);
                    model.RoomTypes = dropDownItemService.GetDropDownItemSelectModels(54);
                    model.TransportTypes = dropDownItemService.GetDropDownItemSelectModels(55);
                    model.HotelTypes = dropDownItemService.GetDropDownItemSelectModels(53);
                    model.AirportNames = dropDownItemService.GetDropDownItemSelectModels(51);
                    model.AirlinesNames = dropDownItemService.GetDropDownItemSelectModels(52);


                    model.AirportDrops = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.AirportPickups = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.IsMakkahZiyarah = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.IsMakkah2Madinah = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.IsMadinahZiyarah = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.HazzPackages = dropDownItemService.GetDropDownItemSelectModels(17);
                    model.ServiceYears = kttlCustomerService.GetServeiceYear();

                }
                else
                {
                    if (!string.IsNullOrEmpty(Session["ClientId"].ToString()))
                    {
                        model.ClientId = Convert.ToInt32(Session["ClientId"]);
                        model.ClientName = Session["FullName"].ToString();
                    }
                    model.ServiceTypes = dropDownItemService.GetDropDownItemSelectModels(16);
                    model.RoomTypes = dropDownItemService.GetDropDownItemSelectModels(54);
                    model.TransportTypes = dropDownItemService.GetDropDownItemSelectModels(55);
                    model.HotelTypes = dropDownItemService.GetDropDownItemSelectModels(53);
                    model.AirportNames = dropDownItemService.GetDropDownItemSelectModels(51);
                    model.AirlinesNames = dropDownItemService.GetDropDownItemSelectModels(52);

                    model.AirportDrops = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.AirportPickups = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.IsMakkahZiyarah = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.IsMakkah2Madinah = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.IsMadinahZiyarah = dropDownItemService.GetDropDownItemSelectModels(56);
                    model.HazzPackages = dropDownItemService.GetDropDownItemSelectModels(17);
                    model.ServiceYears = kttlCustomerService.GetServeiceYear();
                }

                if (id > 0)
                {
                    KttlCustomer _KttlCustomerExist = db.KttlCustomers.Where(x => x.ClientId == model.ClientId).FirstOrDefault();

                    if (_KttlCustomerExist != null)
                    {
                        clientInfo = GetKTTLClientInformation(_KttlCustomerExist.ClientId);
                    }

                }
                ViewBag.clientInfo = clientInfo;
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "KTTLCRM", new { @companyId = 18 });
            }
        }


        // POST: KttlServices/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(KttlServiceModel model)
        {
            if (model.OID <= 0)
            {
                model.ClientId = (int)Session["ClientId"];
                kttlService.SaveKttlService(0, model);
            }
            else
            {
                KttlService kttlService2 = db.KttlServices.FirstOrDefault(x => x.OID == model.OID);
                if (kttlService2 == null)
                {
                    TempData["errMessage1"] = "Data not found!";
                    return RedirectToAction("Create");
                }

                kttlService.SaveKttlService(model.OID, model);
                TempData["DataUpdate"] = "Data Save Successfully!";
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult CreateOrEdit(KttlServiceModel model)
        {
            string redirectPage = string.Empty;

Source/KGERP/Views/KttlServices/Delete.cshtml
@model KGERP.Data.Models.KttlService

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KttlService</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicketNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Passenger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Passenger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TravelClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HazzPackage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HazzPackage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Source/KGERP/Views/KttlServices/Details.cshtml
@model KGERP.Service.ServiceModel.KttlServiceModel
@*@model PagedList.IPagedList<KGERP.Service.ServiceModel.KttlCustomerModel>*@
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>KttlService Details</h3>

<hr style="border-color:red; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TicketNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TicketNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPassenger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPassenger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Currency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Currency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TravelClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HazzPackage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HazzPackage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

        

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.OID }) |*@
    @Html.ActionLink("Back to List", "Index")

    <a href="@Url.Action("CreateOrEdit","KttlServices",new {  clientId = Model.ClientId, id = Model.OID, searchText = ""})" title="Add Service of Client" class="btn btn-info btn-xs">
        <i class="fa fa-plus" style="font-size:15px; color:darkgreen" aria-hidden="true"></i>
    </a>
</p>

Source/KGERP/Views/KttlServices/Edit.cshtml
@model KGERP.Data.Models.KttlService

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KttlService</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OID)

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartureFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartureTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartureDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TicketNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TicketNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HotelAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HotelAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HotelAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Passenger, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Passenger, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Passenger, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Currency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Currency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TravelClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TravelClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TravelClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HazzPackage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HazzPackage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HazzPackage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Source/KGERP/Views/KttlServices/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<KGERP.Service.ServiceModel.KttlServiceModel>
@using PagedList;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    @using (Html.BeginForm("Index", "KttlServices", FormMethod.Get))
    {
        <div class="col-md-3">
            <h4><b>Service List</b></h4>
        </div>
        <div class="col-md-3">
            <div class="col-md-10">@Html.TextBox("searchText", null, new { @autocomplete = "off", @class = "form-control pull-right", @placeholder = "Search..." })</div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-success">Search&nbsp;<i class="fa fa-search"></i></button>
            </div>
        </div>

        @*<div class="col-md-3">
                <a href="@Url.Action("ExportKGREClientToExcel", new { searchText = Request.QueryString["searchText"]  })" title="New Client" class="btn btn-primary pull-right">
                    <span class="glyphicon glyphicon-download"></span> Export Client
                </a>
            </div>*@
        <div class="col-md-3">
            <a href="@Url.Action("CreateOrEdit", new {clientId = 0, id = 0,searchText="" })" title="Add Service" class="btn btn-primary pull-right">
                <span class="glyphicon glyphicon-plus-sign"></span> Add Service
            </a>
        </div>
    }
</div>
<hr style="border-color:red; padding:0px;margin-top: 10px;margin-bottom: 20px; border-width: 2px;" />
<div style="width: 100%; height: 100%; overflow-x: visible; overflow-y: scroll;">
    <style>
        table td th {
            border: solid 1px #fab;
            width: 100px;
            word-wrap: inherit;
        }
    </style>

    <table class="table">
        <tr style="background-color:#009270;color:#FFFFFF">
            <th>
                SL.
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().ClientId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().ClientName)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().ServiceType)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().TicketNo)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().DepartureDate)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().ReturnDate)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().DepartureFrom)
            </th>
            <th nowrap>
                @Html.DisplayNameFor(model => model.First().DepartureTo)
            </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model.Select((x, i) => new { Data = x, Index = i }))
        {
            <tr>
                <td>
                    @((item.Index + 1) + (Model.PageNumber - 1) * Model.PageSize)
                </td>
                <td>
                    @if (@item.Data.ClientId != null)
                    {
                        @Html.DisplayFor(modelItem => item.Data.ClientId)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.ClientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.ServiceType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.TicketNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.DepartureDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.ReturnDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.DepartureFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data.DepartureTo)
                </td>
                <td>
                    <a href="@Url.Action("Details", new { id = item.Data.OID })" title="Details Client" class="btn btn-success btn-xs">
                        Details
                    </a>
                </td>
            </tr>
        }

    </table>
    @if (Model.PageCount > 1)
    {
        <span class="btn btn-success">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        </span>
        <span class="checkbox">
            @Html.PagedListPager(Model, Page_No =>
                Url.Action("Index", "KttlServices",
                new { Page_No, Sorting_Order = Request.QueryString["Search"],
                SearchText = Request.QueryString["searchText"] }))
        </span>
    }
</div>